# Site settings
title: در جست‌وجوی آزادی
author: دانیال بهزادی
email: dani.behzi@ubuntu.com
description: > # this means to ignore newlines until "baseurl:"
  منتشر شده با پروانهٔ CC-BY-SA 
  
  در سال‌های ۱۳۹۳ تا ۱۳۹۵
baseurl: "/weblog" # the subpath of your site, e.g. /blog/
url: "https://danialbehzadi.github.io" # the base hostname & protocol for your site
twitter_username: danialbehzadi
github_username:  danialbehzadi

# Handling Reading
encoding: utf-8

# Outputting
permalink: /:year/:title
paginate: 3
paginate_path: "/page:num/"
timezone: Asia/Tehran

# Build settings

# Conversion
markdown: kramdown
highlighter: pygments
